#!/usr/bin/env python
import sys
sys.path += [ "../.."]
from PyQt4 import QtCore, QtGui
from boadata.trees.file import DirectoryNode
from boadata.gui.qt import MainWindow, DataTreeModel

if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    if len(sys.argv) > 1:
        path = sys.argv[1]
    else:
        path = "~"
    branch = DirectoryNode(path) 
    model = DataTreeModel(branch)
    mw = MainWindow()
    mw.show_tree(model)
    mw.show()
    sys.exit(app.exec_())
