#!/usr/bin/env python

import sys
sys.path += [ "../.."]
from PyQt4 import QtCore, QtGui
from boadata.trees.file import DirectoryNode
from boadata.gui.qt import MainWindow, DataTreeView, DataTreeModel

if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
